version: "3"

services:
  ollert-db:
      image: "postgres:13"
      volumes:
        - ollertdb-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=ollert_db
      ports:
        - "5432:5432"

volumes:
  ollertdb-data:
